spring:
  application:
    name: product-app

  datasource:
    url: jdbc:postgresql://localhost:5432/product-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    create-schemas: true

  sql:
    init:
      mode: never

  thymeleaf:
    cache: false

logging:
  level:
    org.flywaydb: INFO
    org.springframework.jdbc: DEBUG
